# -*- coding: utf-8 -*-
"""task-1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J0zC4xsxcSuN0StAVn8oFjv_IwNOhrz3
"""

# Create a list
my_list = [1, 2, 3, 4, 5]
print("Initial list:", my_list)

# Add an element to the list
my_list.append(6)
print("List after adding an element:", my_list)

# Remove an element from the list
my_list.remove(2)
print("List after removing an element:", my_list)

# Modify an element in the list
my_list[0] = 10
print("List after modifying an element:", my_list)

# Create a dictionary
my_dict = {'a': 1, 'b': 2, 'c': 3}
print("\nInitial dictionary:", my_dict)

# Add a key-value pair to the dictionary
my_dict['d'] = 4
print("Dictionary after adding a key-value pair:", my_dict)

# Remove a key-value pair from the dictionary
del my_dict['b']
print("Dictionary after removing a key-value pair:", my_dict)

# Modify a value in the dictionary
my_dict['a'] = 10
print("Dictionary after modifying a value:", my_dict)

# Create a set
my_set = {1, 2, 3, 4, 5}
print("\nInitial set:", my_set)

# Add an element to the set
my_set.add(6)
print("Set after adding an element:", my_set)

# Remove an element from the set
my_set.remove(3)
print("Set after removing an element:", my_set)

# Modify a set by removing an element and adding another
my_set.discard(2)  # Discard doesn't raise an error if the element is not found
my_set.add(7)
print("Set after modifying elements:", my_set)